### ISSUE TITLE
Hello, I want to know is there some data process before run data_find.py?

### ISSUE THREAD

**Issue by JingqiNiu** [WentianZhang-ML/WDMT-Net#1]
When I see your paper, I find it in the paper, a IDirD image resize to 768×768  , splitinto 3*3 patch and covert to gray space. I don't find any process in data_find.py. So should I process IDRID frist into that format?

**Comment by WentianZhang-ML** [comment]
Sure. You need to resize a IDRiD image to 768×768 pixels and convert it to gray. Then use data_find.py to process data and split it into patches.

**Comment by JingqiNiu** [comment]
So the data_find.py will split it into patches？

**Comment by JingqiNiu** [comment]
And can you prove the train val split for ADAM and IDIRD?

**Comment by WentianZhang-ML** [comment]
We provide an example of split operation in function 'hog_split' in data_find.py. And the input of model is in form of patches.

**Comment by WentianZhang-ML** [comment]
We followed the original protocol of two datasets and you can see the detailed information in their papers.

**Comment by JingqiNiu** [comment]
Thanks a lot

**Comment by WentianZhang-ML** [comment]
If you find it is useful, hopefully give a star to this repository

**Comment by YXtrees** [comment]
> When I see your paper, I find it in the paper, a IDirD image resize to 768×768 , splitinto 3*3 patch and covert to gray space. I don't find any process in data_find.py. So should I process IDRID frist into that format?

请问您的数据集怎么下载的
